x-airflow-common: &airflow-common
  build:
    context: ..
    dockerfile: docker/airflow/Dockerfile
  image: s3-lakehouse-dwh-airflow:local
  environment: &airflow-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__CORE__DAGS_FOLDER: /opt/s3-lakehouse-dwh/airflows/dags
    AIRFLOW__CORE__FERNET_KEY: ""
    AIRFLOW__WEBSERVER__SECRET_KEY: temporary-secret-key
    DWH_CONFIG: /opt/s3-lakehouse-dwh/configs/app_config.yaml
    PYTHONPATH: /opt/s3-lakehouse-dwh
  volumes:
    - ../:/opt/s3-lakehouse-dwh
    - airflow_logs:/opt/airflow/logs
  depends_on:
    postgres:
      condition: service_healthy

services:
  postgres:
    image: postgres:16
    container_name: dwh-postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d airflow"]
      interval: 10s
      timeout: 5s
      retries: 20

  airflow-init:
    <<: *airflow-common
    container_name: dwh-airflow-init
    command: >
      bash -c "airflow db migrate &&
      airflow users create
      --username admin
      --password admin
      --firstname Admin
      --lastname User
      --role Admin
      --email admin@local.com || true"

  airflow-webserver:
    <<: *airflow-common
    container_name: dwh-airflow-webserver
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    command: ["airflow", "webserver"]

  airflow-scheduler:
    <<: *airflow-common
    container_name: dwh-airflow-scheduler
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    command: ["airflow", "scheduler"]

volumes:
  postgres_data:
  airflow_logs:

