project:
  name: AWS Medallion Lakehouse
  environment: dev
  pipeline: olist_medallion_pipeline

aws:
  region: ap-southeast-1
  bucket: olist-lakehouse-data

paths:
  seed: db/seed

s3:
  bronze_prefix: bronze
  silver_prefix: silver
  gold_prefix: gold
  bronze_uri: s3a://olist-lakehouse-data/bronze
  silver_uri: s3a://olist-lakehouse-data/silver
  gold_uri: s3a://olist-lakehouse-data/gold

layers:
  source: db/seed
  bronze: s3://olist-lakehouse-data/bronze
  silver: s3://olist-lakehouse-data/silver
  gold: s3://olist-lakehouse-data/gold

athena:
  database: olist_lakehouse
  workgroup: primary
  output_location: s3://olist-lakehouse-data/athena-results/

spark:
  app_name: OlistSilverClean
  master: local[*]
  hadoop_aws_package: org.apache.hadoop:hadoop-aws:3.4.1
  s3_endpoint: s3.ap-southeast-1.amazonaws.com

tables:
  - olist_customers_dataset
  - olist_geolocation_dataset
  - olist_order_items_dataset
  - olist_order_payments_dataset
  - olist_order_reviews_dataset
  - olist_orders_dataset
  - olist_products_dataset
  - olist_sellers_dataset
  - product_category_name_translation
